### PR TITLE
Updated OMETRIA_API_TEST_URL

### PR DESCRIPTION
**Pull request by mickeypash**
Updated OMETRIA_API_TEST_URL to point to `admin`
Added the follow location flag for `curl`

### CODE REVIEW

**Comment by pedrosland** [comment]
Great. When you get some time can you test that this works? I'm confident but if we're giving this to clients, I'd like to be as close to 100% as possible.

**Comment by pedrosland** [comment]
Great. Thank you.

@electric-al can you take a look at this please? We have successfully tested on Mikey's machine.
Is there a process for releasing a new version?

**Comment by mickeypash** [comment]
@pedrosland I noticed that this was never reviewed or merged 🤔
Do you remember the context of this? Is it still a relevant PR?

**Comment by pedrosland** [comment]
As part of the installation process, the magento extension runs this code. As we moved from console.ometria.com to admin.ometria.com the url was wrong and the code wouldn't handle the redirect :(

You improved the error message so that if it breaks again, we may be able to understand what is going on without having to pepper the extension code with print statements and install it several times ourselves.

**Review by pedrosland — APPROVED** [review]

**Review by electric-al — APPROVED** [review]
All looks good to me. Thanks.

**Pull request merged**
